name: bspm
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - numpy=1.20.3
  - pandas=1.3.1
  - pip=21.2.4
  - python=3.9.6
  - pytorch=1.9.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - pip:
    - torchdiffeq==0.2.2
    - cppimport
    - cython
    - tensorboard
    - sparsesvd